In [45]:
# read the "the-verdict" book from the storage

with open("the-verdict.txt", 'r', encoding='utf-8') as f:
  raw_text = f.read()

print("Total number of character: ", len(raw_text))
print(raw_text[:99])

Total number of character:  20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [46]:
# example to split the raw text read from the book into individual words for preparing tokens

import re

text = 'hello, world. this, is a test.'
result = re.split(r'(\s)', text)
print(result)

['hello,', ' ', 'world.', ' ', 'this,', ' ', 'is', ' ', 'a', ' ', 'test.']


In [47]:
# this is also a part of the example

result = re.split(r'([,.]|\s)', text)
print(result)

['hello', ',', '', ' ', 'world', '.', '', ' ', 'this', ',', '', ' ', 'is', ' ', 'a', ' ', 'test', '.', '']


In [48]:
# we should note that when we split the large sequence of text into invidual words even the white spaces
# are considered as elements of the list so we need to remove them from our list of words

result = [item for item in result if item.strip()]
print(result)

['hello', ',', 'world', '.', 'this', ',', 'is', 'a', 'test', '.']


In [49]:
# tokenizing our raw_text
#1. split the raw_text into individual word
#2. then strip the white spaces

preProcessedText = re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preProcessedText = [item.strip() for item in preProcessedText if item.strip()]
print(preProcessedText[:99])

['I', 'HAD', 'always', 'thought', 'Jack', 'Gisburn', 'rather', 'a', 'cheap', 'genius', '--', 'though', 'a', 'good', 'fellow', 'enough', '--', 'so', 'it', 'was', 'no', 'great', 'surprise', 'to', 'me', 'to', 'hear', 'that', ',', 'in', 'the', 'height', 'of', 'his', 'glory', ',', 'he', 'had', 'dropped', 'his', 'painting', ',', 'married', 'a', 'rich', 'widow', ',', 'and', 'established', 'himself', 'in', 'a', 'villa', 'on', 'the', 'Riviera', '.', '(', 'Though', 'I', 'rather', 'thought', 'it', 'would', 'have', 'been', 'Rome', 'or', 'Florence', '.', ')', '"', 'The', 'height', 'of', 'his', 'glory', '"', '--', 'that', 'was', 'what', 'the', 'women', 'called', 'it', '.', 'I', 'can', 'hear', 'Mrs', '.', 'Gideon', 'Thwing', '--', 'his', 'last', 'Chicago', 'sitter']


In [50]:
# converting tokens(words) into tokenId
all_words = sorted(set(preProcessedText))
vocab_size = len(all_words)
print(vocab_size)
print(all_words)

1130
['!', '"', "'", '(', ')', ',', '--', '.', ':', ';', '?', 'A', 'Ah', 'Among', 'And', 'Are', 'Arrt', 'As', 'At', 'Be', 'Begin', 'Burlington', 'But', 'By', 'Carlo', 'Chicago', 'Claude', 'Come', 'Croft', 'Destroyed', 'Devonshire', 'Don', 'Dubarry', 'Emperors', 'Florence', 'For', 'Gallery', 'Gideon', 'Gisburn', 'Gisburns', 'Grafton', 'Greek', 'Grindle', 'Grindles', 'HAD', 'Had', 'Hang', 'Has', 'He', 'Her', 'Hermia', 'His', 'How', 'I', 'If', 'In', 'It', 'Jack', 'Jove', 'Just', 'Lord', 'Made', 'Miss', 'Money', 'Monte', 'Moon-dancers', 'Mr', 'Mrs', 'My', 'Never', 'No', 'Now', 'Nutley', 'Of', 'Oh', 'On', 'Once', 'Only', 'Or', 'Perhaps', 'Poor', 'Professional', 'Renaissance', 'Rickham', 'Riviera', 'Rome', 'Russian', 'Sevres', 'She', 'Stroud', 'Strouds', 'Suddenly', 'That', 'The', 'Then', 'There', 'They', 'This', 'Those', 'Though', 'Thwing', 'Thwings', 'To', 'Usually', 'Venetian', 'Victor', 'Was', 'We', 'Well', 'What', 'When', 'Why', 'Yes', 'You', '_', 'a', 'abdication', 'able', 'about', 'ab

In [51]:
# create a vocabulaty for the all_words (which are unique words in the preProcessedText)
# vocabulary consists of unique words as key and a unique numerical value of the values
# just like a python dictionay

vocabulary = {token: integer for integer, token in enumerate(all_words)}

In [52]:
# printing first 50 vocabulary
# now we have assigned unique numerical values to unique tokens(words)
# and by doing this we have encoded the tokens into numerical values

for i, item in enumerate(vocabulary.items()):
  print(item)
  if i >= 50:
    break

('!', 0)
('"', 1)
("'", 2)
('(', 3)
(')', 4)
(',', 5)
('--', 6)
('.', 7)
(':', 8)
(';', 9)
('?', 10)
('A', 11)
('Ah', 12)
('Among', 13)
('And', 14)
('Are', 15)
('Arrt', 16)
('As', 17)
('At', 18)
('Be', 19)
('Begin', 20)
('Burlington', 21)
('But', 22)
('By', 23)
('Carlo', 24)
('Chicago', 25)
('Claude', 26)
('Come', 27)
('Croft', 28)
('Destroyed', 29)
('Devonshire', 30)
('Don', 31)
('Dubarry', 32)
('Emperors', 33)
('Florence', 34)
('For', 35)
('Gallery', 36)
('Gideon', 37)
('Gisburn', 38)
('Gisburns', 39)
('Grafton', 40)
('Greek', 41)
('Grindle', 42)
('Grindles', 43)
('HAD', 44)
('Had', 45)
('Hang', 46)
('Has', 47)
('He', 48)
('Her', 49)
('Hermia', 50)


In [53]:
# creating a Tokenizer class with encode and decode method

class SimpleTokenizerv1:
  def __init__(self, vocabulary):
    self.str_to_int = vocabulary
    self.int_to_str = {value: key for key, value in vocabulary.items()}

  def encode(self, text):
    preProcessedText = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preProcessedText = [item.strip() for item in preProcessedText if item.strip()]
    print(f"Before assigning tokenId: \n {preProcessedText}")
    ids = [self.str_to_int[s] for s in preProcessedText]
    return ids

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    print(f"Before removing the spaces infront of punctuations: \n {text}")
    # replace spaces before the specified punctuations
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text

In [54]:
# instantiating tokenizer from the SimpleTokenizer class

tokenizer = SimpleTokenizerv1(vocabulary)
# this text is present in our training set
text = """
        It's the last he painted, you know,"
        Mrs. Gisburn said with pardonable pride.
        """

ids = tokenizer.encode(text)
print(f"After assigning tokenId: \n {ids}")

Before assigning tokenId: 
 ['It', "'", 's', 'the', 'last', 'he', 'painted', ',', 'you', 'know', ',', '"', 'Mrs', '.', 'Gisburn', 'said', 'with', 'pardonable', 'pride', '.']
After assigning tokenId: 
 [56, 2, 850, 988, 602, 533, 746, 5, 1126, 596, 5, 1, 67, 7, 38, 851, 1108, 754, 793, 7]


In [55]:
text = tokenizer.decode(ids)
print(f"Ater removing the spaces infront of punctuations: \n {text}")

Before removing the spaces infront of punctuations: 
 It ' s the last he painted , you know , " Mrs . Gisburn said with pardonable pride .
Ater removing the spaces infront of punctuations: 
 It' s the last he painted, you know," Mrs. Gisburn said with pardonable pride.


In [56]:
# this throws and error because our LLM model has not seen the world "Hello" yet

# text = 'Hello, do you like tea?'
# print(tokenizer.encode(text))

In [57]:
# Adding special context tokens

# In the previous section, we implemented a simple tokenizer and applied it to a passage from the training set,
# in this section, we will modify this tokenizer to handle unknown words
# in particular, we will modify the vocabulary and tokenizer we implemented in the previous section, simpleTokenizerv2

# <|unk|> -> 783 <|endoftext|> -> 784,  these are the token that we are going to include in this section

In [58]:
all_tokens = sorted(list(set(preProcessedText)))
all_tokens.extend(["<|endoftext|>", "<|unk|>"])

vocabulary = {token: integer for integer, token in enumerate(all_tokens)}

In [59]:
len(vocabulary)

1132

In [60]:
for i, item in enumerate(list(vocabulary.items())[-5:]):
  print(i, item)

0 ('younger', 1127)
1 ('your', 1128)
2 ('yourself', 1129)
3 ('<|endoftext|>', 1130)
4 ('<|unk|>', 1131)


In [61]:
# creating a Tokenizer class with encode and decode method

class SimpleTokenizerv2:
  def __init__(self, vocabulary):
    self.str_to_int = vocabulary
    self.int_to_str = {value: key for key, value in vocabulary.items()}

  def encode(self, text):
    preProcessedText = re.split(r'([,.:;?_!"()\']|--|\s)', text)
    preProcessedText = [item.strip() for item in preProcessedText if item.strip()]
    preProcessedText = [
        item if item in self.str_to_int
        else "<|unk|>"
        for item in preProcessedText
    ]
    print(f"Before assigning tokenId: \n {preProcessedText}")
    ids = [self.str_to_int[s] for s in preProcessedText]
    return ids

  def decode(self, ids):
    text = " ".join([self.int_to_str[i] for i in ids])
    print(f"Before removing the spaces infront of punctuations: \n {text}")
    # replace spaces before the specified punctuations
    text = re.sub(r'\s+([,.?!"()\'])', r'\1', text)
    return text

In [62]:
tokenizev2 = SimpleTokenizerv2(vocabulary)

text1 = "Hello, do you like tea?"
text2 = "In the sunlit terraces of the palace."
text = "<|endoftext|>".join((text1, text2))
print(text)
ids = tokenizev2.encode(text)
print(f"After assigning tokenId: \n {ids}")

Hello, do you like tea?<|endoftext|>In the sunlit terraces of the palace.
Before assigning tokenId: 
 ['<|unk|>', ',', 'do', 'you', 'like', 'tea', '?', '<|unk|>', 'the', 'sunlit', 'terraces', 'of', 'the', '<|unk|>', '.']
After assigning tokenId: 
 [1131, 5, 355, 1126, 628, 975, 10, 1131, 988, 956, 984, 722, 988, 1131, 7]


In [63]:
text = tokenizev2.decode(ids)
print(f"Ater removing the spaces infront of punctuations: \n {text}")

Before removing the spaces infront of punctuations: 
 <|unk|> , do you like tea ? <|unk|> the sunlit terraces of the <|unk|> .
Ater removing the spaces infront of punctuations: 
 <|unk|>, do you like tea? <|unk|> the sunlit terraces of the <|unk|>.


In [64]:
# here we are using Byte Pair Encoding (BPE)
# this word compressor algorithm breaks individual
# word in the vocabulary into subwords and single characters

# pip install tiktoken

In [65]:
import importlib
import tiktoken

print(importlib.metadata.version("tiktoken"))

0.9.0


In [66]:
tokenizerTT = tiktoken.get_encoding("gpt2")

In [67]:
strings = "hello there i am using whatsapp <|endoftext|> this is a new text from different source"

ids = tokenizerTT.encode(strings, allowed_special={"<|endoftext|>"})
print(ids)

[31373, 612, 1312, 716, 1262, 45038, 1324, 220, 50256, 428, 318, 257, 649, 2420, 422, 1180, 2723]


In [68]:
strings = tokenizerTT.decode(ids)
print(strings)

hello there i am using whatsapp <|endoftext|> this is a new text from different source


In [69]:
# creating input-target pairs

In [70]:
with open("the-verdict.txt", 'r', encoding='utf-8') as f:
  raw_text = f.read()

enc_text = tokenizerTT.encode(raw_text)
print(len(enc_text))

5145


In [71]:
print(enc_text)

[40, 367, 2885, 1464, 1807, 3619, 402, 271, 10899, 2138, 257, 7026, 15632, 438, 2016, 257, 922, 5891, 1576, 438, 568, 340, 373, 645, 1049, 5975, 284, 502, 284, 3285, 326, 11, 287, 262, 6001, 286, 465, 13476, 11, 339, 550, 5710, 465, 12036, 11, 6405, 257, 5527, 27075, 11, 290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976, 13, 357, 10915, 314, 2138, 1807, 340, 561, 423, 587, 10598, 393, 28537, 2014, 198, 198, 1, 464, 6001, 286, 465, 13476, 1, 438, 5562, 373, 644, 262, 1466, 1444, 340, 13, 314, 460, 3285, 9074, 13, 46606, 536, 5469, 438, 14363, 938, 4842, 1650, 353, 438, 2934, 489, 3255, 465, 48422, 540, 450, 67, 3299, 13, 366, 5189, 1781, 340, 338, 1016, 284, 3758, 262, 1988, 286, 616, 4286, 705, 1014, 510, 26, 475, 314, 836, 470, 892, 286, 326, 11, 1770, 13, 8759, 2763, 438, 1169, 2994, 284, 943, 17034, 318, 477, 314, 892, 286, 526, 383, 1573, 11, 319, 9074, 13, 536, 5469, 338, 11914, 11, 33096, 663, 4808, 3808, 62, 355, 996, 484, 547, 12548, 287, 281, 13079, 410, 12523, 286, 

In [72]:
enc_sample = enc_text[50:]

In [73]:
context_size = 4

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:    {y}")

x: [290, 4920, 2241, 287]
y:    [4920, 2241, 287, 257]


In [74]:
for i in range(1, context_size+1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257


In [75]:
for i in range(1, context_size+1):
  context = enc_sample[:i]
  desired = enc_sample[i]

  print(tokenizerTT.decode(context), "---->", tokenizerTT.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a


In [76]:
# implementing an efficient DataLoader

In [84]:
 import torch
 from torch.utils.data import Dataset, DataLoader

In [85]:
class GPTDatasetv1(Dataset):

  # creating input and target tensors by looping through our entire dataset

  def __init__(self, txt, tokenizerTT, max_length, stride):
    self.input_ids = []
    self.target_ids = []

    token_ids = tokenizerTT.encode(txt, allowed_special={"<|endoftext|>"})

    for i in range(0, len(token_ids) - max_length, stride):
      input_chunk = token_ids[i: i + max_length]
      target_chunk = token_ids[i+1: i + max_length+1]
      self.input_ids.append(torch.tensor(input_chunk))
      self.target_ids.append(torch.tensor(target_chunk))

  def __len__(self):
    return len(self.input_ids)

  # returns input and target tensors of the given index
  def __getitem__(self, idx):
    return self.input_ids[idx], self.target_ids[idx]

In [86]:
def create_DataLoaderv1(txt, batch_size=4, max_length=256,
                        stride=128, shuffle=True, drop_last=True,
                        num_workers=0):

  # initialize the tokenizer
  tokenizerNew = tiktoken.get_encoding("gpt2")

  # create the dataset
  dataset = GPTDatasetv1(txt, tokenizerNew, max_length, stride)

  # create the DataLoader
  dataloader = DataLoader(dataset,
                          batch_size=batch_size,
                          shuffle=shuffle,
                          drop_last=drop_last,
                          num_workers=num_workers)
  return dataloader




In [87]:
with open("the-verdict.txt", 'r', encoding='utf-8') as f:
  raw_text = f.read()



In [88]:
import torch
print("PyTorch version", torch.__version__)

dataloader = create_DataLoaderv1(raw_text, batch_size=1, max_length=4, stride=1, shuffle=False)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version 2.6.0+cu124
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [97]:
import torch

vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

print(token_embedding_layer)

Embedding(50257, 256)


In [98]:
max_length = 4
dataloader = create_DataLoaderv1(
    raw_text, batch_size = 8, max_length=max_length,
    stride = 4, shuffle = False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

In [100]:
print(inputs)
print(targets)

tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])
tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [93]:
print(inputs.shape)

torch.Size([8, 4])


In [101]:
token_embeddings = token_embedding_layer(inputs)
print(token_embeddings)

tensor([[[-6.5975e-02, -2.0968e+00, -4.2585e-01,  ..., -5.8353e-01,
          -6.3481e-01,  5.1604e-01],
         [-2.0977e+00,  2.2354e+00, -2.3548e-01,  ...,  2.2764e-01,
          -5.7396e-01, -5.6518e-01],
         [ 3.0422e-01,  1.4231e+00, -1.7771e+00,  ..., -1.3549e+00,
          -2.7694e+00,  2.9293e-02],
         [-7.4564e-01,  5.0311e-01, -1.2219e+00,  ..., -6.3146e-01,
          -1.6663e+00, -1.7800e+00]],

        [[ 5.1709e-01, -1.7236e+00, -7.3325e-01,  ..., -7.6882e-01,
           3.3141e-01,  8.4318e-01],
         [ 4.3576e-01,  7.8883e-01, -1.9351e+00,  ..., -9.3559e-02,
           2.5367e-01,  5.7783e-01],
         [-7.8212e-01, -1.7248e+00, -6.1234e-01,  ...,  6.4315e-01,
          -1.0009e+00, -1.7804e-01],
         [-7.4066e-01,  2.7807e-01,  2.7311e-01,  ...,  1.1091e-01,
          -1.3318e+00,  8.2717e-01]],

        [[ 1.0119e+00, -1.8218e+00, -9.2531e-01,  ...,  4.0315e-01,
          -7.2411e-01, -4.9703e-01],
         [-3.0389e-01, -4.4332e-01,  7.0176e-01,  .

In [95]:
context_length = max_length

pas_embedding_layer = torch.nn.Embedding(context_length, output_dim)

In [105]:
pos_embeddings = pas_embedding_layer(torch.arange(max_length))
pos_embeddings

tensor([[ 0.2680, -2.7336,  0.0261,  ..., -0.1502,  1.7960, -0.4099],
        [-0.3649,  2.3751,  1.2746,  ..., -1.6109, -0.2158,  0.7788],
        [-0.0899, -0.8206,  0.3915,  ...,  0.4080, -0.2766,  0.8085],
        [-1.5714,  0.7291,  0.1229,  ..., -0.6462, -0.1352, -0.7258]],
       grad_fn=<EmbeddingBackward0>)

In [103]:
pos_embeddings.shape

torch.Size([4, 256])